version: '3'
services:
  influxdb:
    image: influxdb:latest
    volumes:
      - influxdb-data:/var/lib/influxdb2
    ports:
      - "8086:8086"  # InfluxDB HTTP API port
    env_file:
      - .env

  grafana:
    image: grafana/grafana
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    env_file:
      - .env

  config-db:
    image: postgres:latest
    volumes:
      - config-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

volumes:
  influxdb-data:
  grafana-data:
  config-db-data: