version: '3'
services:
  mqtt-broker:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"   # Default MQTT port
    volumes:
      - ./mosquitto-data:/mosquitto/data
      - ./mosquitto-config:/mosquitto/config

  influxdb:
    image: influxdb:latest
    environment:
      - INFLUXDB_DB=telemetry_db
      - INFLUXDB_USER=telemetry_user
      - INFLUXDB_PASSWORD=your_strong_password
    volumes:
      - ./influxdb-data:/var/lib/influxdb2
    ports:
      - "8086:8086"  # InfluxDB HTTP API port

  grafana:
    image: grafana/grafana
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-data:/var/lib/grafana

  config-db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=config_user
      - POSTGRES_PASSWORD=your_strong_password
      - POSTGRES_DB=config_db
    volumes:
      - ./config-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"